kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "sample-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/piggyvenus/test-rhoar3"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: testJenkinsfile
